name: Run Laravel Tests with File Integrity Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: ""

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: laravel
          MYSQL_ALLOW_EMPTY_PASSWORD: true
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo, mysql
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Check required files
        run: |
          echo "🔍 Verifying critical files exist..."

          # Check .env.example
          if [ ! -f ".env.example" ]; then
            echo "❌ .env.example is missing."
            exit 1
          fi

          # Check if any migration files exist
          if [ -z "$(ls -A database/migrations/*.php 2>/dev/null)" ]; then
            echo "❌ No migration files found in database/migrations/"
            exit 1
          fi

          # Optional: Check if composer.lock exists
          if [ ! -f "composer.lock" ]; then
            echo "❌ composer.lock is missing. Did you forget to commit it?"
            exit 1
          fi

          echo "✅ All required files are present."

      - name: Prepare .env
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Run database migrations
        run: php artisan migrate --force

      - name: Run Laravel tests
        run: php artisan test
